### ISSUE TITLE
Pretty-printing JSON?

### ISSUE THREAD

**Issue by tomasr8** [PyCQA/flake8-json#43]
> By default, the output is not pretty-printed. We would love to add that as a separate formatter option, though.

Hello, are you still interested in adding support for pretty-printing the output?
If so, I'd be happy to contribute this option :)

**Comment by asottile** [comment]
I'm not sure it's possible -- but if you can make it happen by all means

**Comment by tomasr8** [comment]
Maybe I'm missing something, but why wouldn't it be possible?

**Comment by asottile** [comment]
flake8 formatters are run linewise

**Comment by tomasr8** [comment]
Hmm it seems to me that just modifying the default formatter to use proper indentation/new lines should be enough? Each violation can even be preformatted with `json.dumps`

**Comment by asottile** [comment]
sure I mean like I said if you can make it happen by all means go for it

**Comment by asottile** [comment]
via #45
